# Generated by Django 3.2 on 2021-04-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_user'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AddField(
            model_name='product',
            name='carts',
            field=models.ManyToManyField(related_name='products', to='cart.Cart'),
        ),
    ]
