# Generated by Django 3.2 on 2021-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_carts'),
        ('cart', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='cart', to='product.Product'),
        ),
    ]
