# Generated by Django 3.2 on 2021-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_user'),
        ('product', '0002_auto_20210501_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carts',
            field=models.ManyToManyField(blank=True, related_name='products', to='cart.Cart'),
        ),
    ]
